config/routes.rb
WineReview::Application.routes.draw do
  
  resources :wines do
    resources :log_entries
    get 'page/:page', :action => :index, :on => :collection
  end
  root 'wines#index'

end

app/models/log_entry.rb
class LogEntry < ActiveRecord::Base
  belongs_to :wine

  RATINGS = 1..10

  validates :name, :rating, :location, :comments, :tasted_on, presence: true
  validates :rating, inclusion: { in: RATINGS, message: "must be from #{RATINGS.first} to #{RATINGS.last}" }

end

app/models/wine.rb
class Wine < ActiveRecord::Base
	has_many :log_entries, dependent: :destroy
	include ActiveModel::Validations

	VARIETALS = ["Barbera", "Chardonnay", "Merlot"]

	validates :name, :year, :country, presence: true

	validates :year,
				numericality: {only_integer: true},
				if: "year.present?"

	validates :varietal,
				inclusion: {in: VARIETALS,
				message: "%{value} is not a valid varietal"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout ->(controller) { controller.request.xhr? ? false : 'application' }
end

app/controllers/log_entries_controller.rb
class LogEntriesController < ApplicationController
	before_action :set_wine

def index
  @log_entries = @wine.log_entries.order('created_at desc')
end

def new
	@log_entry = @wine.log_entries.new
end

def create
	@log_entry = @wine.log_entries.new(log_entries_params)
	if @log_entry.save
		redirect_to wine_log_entries_path(@wine), notice: 'Log Entry saved!'
	else
		render :new
	end
end






private

def log_entries_params
	params.require(:log_entry).permit(:name, :rating, :location, :comments, :tasted_on)
end

def set_wine
  @wine = Wine.find(params[:wine_id])
end

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
	before_action :set_wine, only: [ :show, :edit, :update, :destroy ]

  def index
  	@wines = Wine.order(:name).page(params[:page])
  end

  def show
  	
  end

  def new
  	@wine = Wine.new
  end

  def create
  	@wine = Wine.new(wine_params)
  	if @wine.save
  		redirect_to @wine, notice: "#{@wine.name} was created successfully!"
  	else
  		render :new
  	end
  end 

  def edit 
  	
  end

  def update
  	if @wine.update(wine_params)
  		redirect_to @wine, notice: "#{@wine.name} was edited successfully!"
  	else
  		render :edit
  	end
  end

  def destroy
  	@wine.destroy
  	redirect_to wines_path
  end

  private

  def wine_params
  	params.require(:wine).permit(:name, :year, :winery, :country, :varietal)
  end

  def set_wine
  	@wine = Wine.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/log_entries_helper.rb
module LogEntriesHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <h3 class="text-center text-muted">For Educational Uses Only</h3>
  </div>
</nav>

app/views/layouts/_header.html.erb
<header class="page-header">
<h1><%= link_to('Wonder Wines', root_path) %></h1>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wonder Wines <%= yield :name %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= render '/layouts/header' %>
</div>
<div class="container">
	<%= render '/shared/flashes' %>
	<%= yield %>
</div>
<%= render '/layouts/footer' %>


</body>
</html>

app/views/log_entries/_form.html.erb
<%= form_for( [ @wine, @log_entry ] ) do |f| %>
  <%= render 'shared/validation_errors', object: @log_entry %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, placeholder: 'Name' %><br />
  <%= f.label :location %> <%= f.text_field :location %><br />
  <%= f.label :rating %>  
  <% LogEntry::RATINGS.each do |rating| %>
    <%= f.radio_button :rating, rating %> <%= rating %>
  <% end %><br />
  <%= f.date_select :tasted_on %>
  <%= f.label :comments %><br/>
  <%= f.text_area :comments %><br/>
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', wine_log_entries_path(@wine), id: 'cancel_log_entry' %>
  </p>

<% end %>

app/views/log_entries/index.html.erb
<header>Log Entries for <%= link_to(@wine.name, @wine) %></header>
<ol id="log_entries">
  <% @log_entries.each do |log_entry| %>
    <li>
      <span class="log_entry"><%= log_entry.rating %> out of 10</span>
      <span class="user">by <%= log_entry.name %> </span>
      <span class="date">
        <%= time_ago_in_words(log_entry.tasted_on) %> ago
      </span>
      <span class="location">from <%= log_entry.location %> </span>
      <p>
        &quot;<%= log_entry.comments %>&quot;
      </p>
    </li>
  <% end %>
</ol>

<%= link_to 'Write a Log Entry', new_wine_log_entry_path(@wine), 
    remote: true,
    data: { 'update-target' => 'review_form_container' },
    class: 'btn btn-primary' %>

  <div id="review_form_container"></div>

app/views/log_entries/new.html.erb
<h1>Write a log entry for <%= @wine.name%></h1>
<%= render 'form' %>

app/views/shared/_flashes.html.erb
<% if flash.present? %>
  <div id="flashes">
    <% flash.each do |key, value| %>
      <p class="flash <%= key %>"><%= value %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_validation_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    Oops! The <%= object.class.name.humanize.downcase %> could not be saved.<br />
    Correct the following <%= pluralize(object.errors.count, "error") %>:
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/wines/_form.html.erb
<%= render 'shared/validation_errors', object: @wine %>
<%= form_for(@wine) do |w| %>
	<%= w.label :name %> <%= w.text_field :name, autofocus: true %> <br />
	<%= w.label :year %> <%= w.text_field :year %><br />
	<%= w.label :winery %> <%= w.text_field :winery %><br />
	<%= w.label :country %> <%= w.text_field :country %><br />
	<%= w.label :varietal %> <%= w.select :varietal, Wine::VARIETALS, { prompt: "Pick one" } %><br />
	<p>
		<%= w.submit %>
		<%= link_to("Canel", wines_path) %>
	</p>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine <%= @wine.name %></h1>
<%= render 'form' %>

app/views/wines/index.html.erb
<h1>Wines</h1>

<%= page_entries_info @wines %>
<ol>
<% @wines.each do |wine| %>
<li><label>Name: </label><%= link_to(wine.name, wine) %></li>
<ul>
<li><label>Winery: </label><%= wine.winery %></li>
<li><label>Varietal: </label><%= wine.varietal %></li>
</ul>
<% end %>
</ol>
<%= paginate @wines %>

<%= link_to("Create New", new_wine_path) %>

app/views/wines/new.html.erb
<h1>Create a New Wine</h1>
<%= render 'form' %>

app/views/wines/show.html.erb
<% content_for :name, @wine.name %>
<h1><%= @wine.name %></h1>

<ul>
<li><label>Year: </label><%= @wine.year %></li>
<li><label>Winery: </label><%= @wine.winery %></li>
<li><label>Country: </label><%= @wine.country %></li>
<li><label>Varietal: </label><%= @wine.varietal %></li>
</ul>

<%= link_to("All Wines", wines_path) %> |
<%= link_to("Edit", edit_wine_path(@wine)) %> 

<p>
  Read all
  <%= link_to pluralize(@wine.log_entries.size, 'rating'), 
                        wine_log_entries_path(@wine) %>
</p>


<%= button_to("Delete", @wine, method: :delete, data:{confirm: 'Are you sure?'}) %>